import type { ContentPack } from './types.js';

export const generalPack: ContentPack = {
  id: 'general',
  name: 'General Practice',
  description: 'Code-themed drills for developers',
  drills: [
    // =============================================
    // WORDS — regular English text, speed builders
    // =============================================
    { id: 'g:words:1', text: 'the quick brown fox jumps over the lazy dog', category: 'words', tags: ['speed-builder', 'common-words'], difficulty: 'beginner' },
    { id: 'g:words:2', text: 'pack my box with five dozen liquor jugs', category: 'words', tags: ['speed-builder', 'common-words'], difficulty: 'beginner' },
    { id: 'g:words:3', text: 'how vexingly quick daft zebras jump', category: 'words', tags: ['speed-builder', 'common-words'], difficulty: 'beginner' },
    { id: 'g:words:4', text: 'fix bugs ship code write tests deploy fast', category: 'words', tags: ['speed-builder'], difficulty: 'beginner' },
    { id: 'g:words:5', text: 'merge main rebase push pull fetch clone init', category: 'words', tags: ['speed-builder'], difficulty: 'beginner' },
    { id: 'g:words:6', text: 'the server crashed right before the demo started', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:7', text: 'always write tests before you refactor anything', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:8', text: 'the database migration failed on production again', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:9', text: 'we need to fix the memory leak before shipping', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:10', text: 'code review found three bugs and a security issue', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:11', text: 'the build passed but staging is still broken somehow', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:12', text: 'deployment takes forever because nobody optimized the pipeline', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:13', text: 'she refactored the entire auth module over the weekend', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:14', text: 'the model started hallucinating after the context window filled up', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:15', text: 'it works on my machine is not a valid deployment strategy', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:16', text: 'sphinx of black quartz judge my vow', category: 'words', tags: ['speed-builder', 'common-words'], difficulty: 'beginner' },
    { id: 'g:words:17', text: 'waltz bad nymph for quick jigs vex', category: 'words', tags: ['speed-builder', 'common-words'], difficulty: 'beginner' },
    { id: 'g:words:18', text: 'jackdaws love my big sphinx of quartz', category: 'words', tags: ['speed-builder', 'common-words'], difficulty: 'beginner' },
    { id: 'g:words:19', text: 'read write edit save commit push deploy ship', category: 'words', tags: ['speed-builder'], difficulty: 'beginner' },
    { id: 'g:words:20', text: 'cache miss retry timeout fallback circuit breaker', category: 'words', tags: ['speed-builder'], difficulty: 'beginner' },
    { id: 'g:words:21', text: 'the bug only reproduces in production on tuesdays', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:22', text: 'nobody remembers who wrote the original auth code', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:23', text: 'the intern deleted the wrong branch and pushed force', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:24', text: 'our staging environment has been down since last friday', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:25', text: 'the legacy code has comments older than most of the team', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:26', text: 'quick standup update the deploy is blocked on review', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:27', text: 'i need one more hour before the sprint demo starts', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:28', text: 'can we move the retro to thursday afternoon instead', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:29', text: 'my blocker is waiting on the design team final specs', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:30', text: 'please add this ticket to the backlog for next sprint', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:31', text: 'the model refused my prompt so i rephrased it three times', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:32', text: 'copilot wrote the test but it passes for the wrong reason', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:33', text: 'the agent kept looping on the same tool call forever', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:34', text: 'my context window is full and i still have not found the bug', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:35', text: 'the embeddings drift every time we update the model version', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:36', text: 'we traced the leak to a forgotten event listener in the modal', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:37', text: 'it turned out to be a dns issue because it is always dns', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:38', text: 'the null check was in the wrong branch of the conditional', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:39', text: 'a race condition caused the counter to skip every tenth value', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:40', text: 'the off by one error hid behind three layers of abstraction', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:41', text: "whose code is this, and why doesn't it have any tests?", category: 'words', tags: ['punctuation'], difficulty: 'intermediate' },
    { id: 'g:words:42', text: "it's not a bug, it's an undocumented feature (probably).", category: 'words', tags: ['punctuation'], difficulty: 'intermediate' },
    { id: 'g:words:43', text: 'ship it, fix it, forget it, repeat the cycle forever.', category: 'words', tags: ['punctuation'], difficulty: 'beginner' },
    { id: 'g:words:44', text: 'the spec says one thing, the docs say another, the code does neither.', category: 'words', tags: ['punctuation'], difficulty: 'intermediate' },
    { id: 'g:words:45', text: "don't push to main, don't force push, don't skip review.", category: 'words', tags: ['punctuation'], difficulty: 'intermediate' },
    { id: 'g:words:46', text: 'refactor, rename, reorganize, then realize you broke everything', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:47', text: 'naming things is hard and cache invalidation is harder', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:48', text: 'premature optimization is the root of all evil they say', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:49', text: 'the simplest solution is usually the one you think of last', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:50', text: 'every abstraction leaks eventually and this one is leaking now', category: 'words', tags: ['common-words'], difficulty: 'advanced' },

    // Dev war stories and AI/ML culture (+50 for 0.1.2)
    { id: 'g:words:51', text: 'the agent spent thirty minutes arguing with itself before giving up', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:52', text: 'we shipped a fix that made the bug worse but in a different file', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:53', text: 'the flaky test passed on the third retry and nobody asked why', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:54', text: 'the incident started at three in the morning as all incidents do', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:55', text: 'the config file had been wrong for six months before anyone noticed', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:56', text: 'a senior engineer rewrote the whole module and it still had the same bug', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:57', text: 'the only person who understood the system left the company last year', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:58', text: 'we added logging everywhere and the bug vanished before we could see it', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:59', text: 'the rollback took longer than the original deploy and broke staging too', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:60', text: 'someone wrote a cron job in 2015 and it is still paying our salaries', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:61', text: 'the vector store returned the right answer to the wrong question again', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:62', text: 'prompt engineering is just begging a model in different fonts', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:63', text: 'the model confidently invented a library that does not exist', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:64', text: 'fine tuning made it worse at everything except the training examples', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:65', text: 'rag pipeline retrieved the outdated doc instead of the canonical one', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:66', text: 'token usage spiked when the assistant quoted the entire file back', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:67', text: 'the evals looked green but production users were very much not green', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:68', text: 'temperature zero still found three novel ways to be wrong', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:69', text: 'we ran the evals and then ran them again and got different numbers', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:70', text: 'every week a new model drops and we re-benchmark the whole stack', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:71', text: 'the pull request touched forty seven files and claimed to be a small fix', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:72', text: 'someone approved my pr in six seconds which is either praise or betrayal', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:73', text: 'the reviewer left twenty nits and one actually important comment', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:74', text: 'open source maintainers are tired and you are about to file issue number ten', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:75', text: 'the readme said it was beta but everyone in production is using it', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:76', text: 'a dependency updated and the world ended for exactly fifteen minutes', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:77', text: 'the changelog said breaking change in a font size too small to read', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:78', text: 'a maintainer renamed the main function and a thousand tests exploded', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:79', text: 'the community forked the project on a tuesday and nobody has spoken since', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:80', text: 'we hit the rate limit on the api and quietly blamed the user', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:81', text: 'clean code is a lifestyle we all admire from a respectful distance', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:82', text: 'typing fast is a side effect of knowing what you want to say', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:83', text: 'ship slow think fast or ship fast think later either works honestly', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:84', text: 'two programmers debug together at half the speed with double the jokes', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:85', text: 'writing tests feels slow until you spend a weekend in the debugger', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:86', text: 'a focused hour beats a distracted day and a distracted day beats nothing', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:87', text: 'every senior engineer was once a junior who googled how to exit vim', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:88', text: 'a junior engineer asked a good question and the whole team paused', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:89', text: 'the best code review starts with thanks this is really clear', category: 'words', tags: ['common-words'], difficulty: 'beginner' },
    { id: 'g:words:90', text: 'pair programming is two people agreeing the problem is harder than expected', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:91', text: "it's wild how much of engineering is just reading logs until a pattern emerges.", category: 'words', tags: ['punctuation'], difficulty: 'advanced' },
    { id: 'g:words:92', text: "oh, right — that's a feature, not a bug, according to yesterday's standup.", category: 'words', tags: ['punctuation'], difficulty: 'advanced' },
    { id: 'g:words:93', text: "someone (and we will never know who) rebased over the release branch.", category: 'words', tags: ['punctuation'], difficulty: 'advanced' },
    { id: 'g:words:94', text: "we're at 'mostly works', which is better than 'sometimes works' — ship it.", category: 'words', tags: ['punctuation'], difficulty: 'advanced' },
    { id: 'g:words:95', text: "everyone's favorite debugging tool is still print, if we're being honest.", category: 'words', tags: ['punctuation'], difficulty: 'intermediate' },
    { id: 'g:words:96', text: 'the rubber duck heard me out and then i realized what i was doing wrong', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:97', text: 'on good days the code writes itself and on bad days it writes you', category: 'words', tags: ['common-words'], difficulty: 'intermediate' },
    { id: 'g:words:98', text: 'the hotfix branch outlived the sprint the feature it was patching', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:99', text: 'tech debt compounds quietly while you promise to clean it up next quarter', category: 'words', tags: ['common-words'], difficulty: 'advanced' },
    { id: 'g:words:100', text: 'the best feature you ever shipped is the one nobody had to learn to use', category: 'words', tags: ['common-words'], difficulty: 'advanced' },

    // =============================================
    // CODE — JS/TS snippets, programming patterns
    // =============================================
    { id: 'g:code:1', text: "const name = 'hello'; let count = 0;", category: 'code', tags: ['code-js'], difficulty: 'beginner' },
    { id: 'g:code:2', text: 'function add(a, b) { return a + b; }', category: 'code', tags: ['code-js'], difficulty: 'beginner' },
    { id: 'g:code:3', text: 'if (x > 10) { console.log(x); }', category: 'code', tags: ['code-js'], difficulty: 'beginner' },
    { id: 'g:code:4', text: "const obj = { key: 'value', num: 42 };", category: 'code', tags: ['code-js'], difficulty: 'beginner' },
    { id: 'g:code:5', text: 'let items = [1, 2, 3, 4, 5];', category: 'code', tags: ['code-js'], difficulty: 'beginner' },
    { id: 'g:code:6', text: 'const result = arr.map(x => x * 2).filter(x => x > 5);', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:7', text: 'async function fetchData(url) { return await fetch(url); }', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:8', text: "import { useState, useEffect } from 'react';", category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:9', text: 'export default class App extends Component {}', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:10', text: 'try { await db.query(sql); } catch (err) { log(err); }', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:11', text: 'const handler = async (req, res) => { res.json({ ok: true }); };', category: 'code', tags: ['code-js'], difficulty: 'advanced' },
    { id: 'g:code:12', text: "const { data, error } = await supabase.from('users').select('*');", category: 'code', tags: ['code-js'], difficulty: 'advanced' },
    { id: 'g:code:13', text: 'type Result<T> = { ok: true; value: T } | { ok: false; error: Error };', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:14', text: 'const debounce = (fn, ms) => { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; };', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:15', text: "app.get('/api/users/:id', auth, async (req, res) => {});", category: 'code', tags: ['code-js'], difficulty: 'advanced' },
    { id: 'g:code:16', text: 'for (let i = 0; i < arr.length; i++) { sum += arr[i]; }', category: 'code', tags: ['code-general'], difficulty: 'intermediate' },
    { id: 'g:code:17', text: 'while (queue.length > 0) { const item = queue.shift(); }', category: 'code', tags: ['code-general'], difficulty: 'intermediate' },
    { id: 'g:code:18', text: 'switch (action.type) { case "ADD": return [...state, item]; }', category: 'code', tags: ['code-general'], difficulty: 'intermediate' },
    { id: 'g:code:19', text: 'interface User { id: string; name: string; email: string; }', category: 'code', tags: ['code-general'], difficulty: 'intermediate' },
    { id: 'g:code:20', text: 'enum Status { Pending, Active, Completed, Failed }', category: 'code', tags: ['code-general'], difficulty: 'beginner' },
    { id: 'g:code:21', text: '() => {} || && !== === ?? ?. ... []', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:22', text: '<div className={styles.container}>{children}</div>', category: 'code', tags: ['symbols', 'code-js'], difficulty: 'intermediate' },
    { id: 'g:code:23', text: '{ ...prev, [key]: value, items: [...prev.items, item] }', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:24', text: '(a: number, b: number): number => a + b;', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:25', text: 'arr.reduce((acc, cur) => ({ ...acc, [cur.id]: cur }), {});', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:26', text: '`${user.name} <${user.email}> (${user.role})`', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:27', text: 'a && b || c ?? d !== e && !f', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:28', text: 'obj?.nested?.deep?.value ?? fallback', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:29', text: '/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+$/', category: 'code', tags: ['symbols'], difficulty: 'advanced' },
    { id: 'g:code:30', text: 'matrix[i][j] = grid[i - 1][j] + grid[i][j - 1];', category: 'code', tags: ['symbols', 'code-general'], difficulty: 'intermediate' },
    { id: 'g:code:31', text: "console.error('Error:', err.message ?? 'unknown');", category: 'code', tags: ['punctuation', 'code-js'], difficulty: 'intermediate' },
    { id: 'g:code:32', text: '// TODO: refactor this; it works but is O(n^2)', category: 'code', tags: ['punctuation', 'code-general'], difficulty: 'intermediate' },
    { id: 'g:code:33', text: 'const [count, setCount] = useState(0);', category: 'code', tags: ['code-js'], difficulty: 'beginner' },
    { id: 'g:code:34', text: 'useEffect(() => { document.title = `${count}`; }, [count]);', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:35', text: 'const memo = useMemo(() => compute(data), [data]);', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:36', text: 'const handleClick = useCallback(() => setOpen(true), []);', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:37', text: 'const ref = useRef<HTMLInputElement>(null);', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:38', text: 'function useToggle(initial = false) { const [v, s] = useState(initial); return [v, () => s(!v)] as const; }', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:39', text: 'function identity<T>(arg: T): T { return arg; }', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:40', text: 'type Partial<T> = { [P in keyof T]?: T[P] };', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:41', text: 'function pluck<T, K extends keyof T>(o: T, k: K): T[K] { return o[k]; }', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:42', text: 'type Readonly<T> = { readonly [P in keyof T]: T[P] };', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:43', text: 'if err != nil { return fmt.Errorf("read: %w", err) }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:44', text: 'go func() { defer wg.Done(); worker(ch) }()', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:45', text: 'ch := make(chan int, 10)', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'beginner' },
    { id: 'g:code:46', text: 'type User struct { ID int `json:"id"`; Name string `json:"name"` }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:47', text: 'for i, v := range items { fmt.Println(i, v) }', category: 'code', tags: ['code-general'], difficulty: 'intermediate' },
    { id: 'g:code:48', text: 'squares = [x * x for x in range(10) if x % 2 == 0]', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:49', text: '@staticmethod\ndef greet(name): return f"hello, {name}"', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:50', text: 'with open("data.txt", "r") as f: lines = f.readlines()', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:51', text: 'print(f"total: {sum(values):.2f} ({len(values)} items)")', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:52', text: 'def fib(n): return n if n < 2 else fib(n-1) + fib(n-2)', category: 'code', tags: ['code-general'], difficulty: 'intermediate' },
    { id: 'g:code:53', text: 'match result { Ok(v) => println!("{}", v), Err(e) => eprintln!("{}", e) }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:54', text: 'let x: Option<i32> = Some(42);', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:55', text: 'impl Display for Point { fn fmt(&self, f: &mut Formatter) -> Result { write!(f, "({}, {})", self.x, self.y) } }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:56', text: 'fn main() { println!("hello, world"); }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'beginner' },
    { id: 'g:code:57', text: 'let v: Vec<i32> = (1..=10).collect();', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:58', text: 'SELECT id, name FROM users WHERE active = 1;', category: 'code', tags: ['code-general'], difficulty: 'beginner' },
    { id: 'g:code:59', text: 'SELECT u.name, COUNT(*) FROM users u JOIN orders o ON o.user_id = u.id GROUP BY u.name;', category: 'code', tags: ['code-general'], difficulty: 'advanced' },
    { id: 'g:code:60', text: 'SELECT *, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) FROM staff;', category: 'code', tags: ['code-general'], difficulty: 'advanced' },
    { id: 'g:code:61', text: 'UPDATE posts SET views = views + 1 WHERE id = ?;', category: 'code', tags: ['code-general'], difficulty: 'beginner' },
    { id: 'g:code:62', text: 'CREATE INDEX idx_user_email ON users(email);', category: 'code', tags: ['code-general'], difficulty: 'intermediate' },
    { id: 'g:code:63', text: '/^https?:\\/\\/[\\w.-]+(:\\d+)?(\\/[\\w.-]*)*\\/?$/', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:64', text: '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:65', text: '/^\\d{4}-\\d{2}-\\d{2}$/', category: 'code', tags: ['symbols', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:66', text: 'const { name, age, ...rest } = user;', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:67', text: 'const [first, second, ...others] = items;', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:68', text: 'const merged = { ...defaults, ...overrides };', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'beginner' },
    { id: 'g:code:69', text: 'fetch(url).then(r => r.json()).then(data => render(data));', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:70', text: 'const [a, b, c] = await Promise.all([fa(), fb(), fc()]);', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:71', text: 'await new Promise(resolve => setTimeout(resolve, 1000));', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:72', text: 'for await (const chunk of stream) { process(chunk); }', category: 'code', tags: ['code-js'], difficulty: 'advanced' },
    { id: 'g:code:73', text: 'export const add = (a: number, b: number) => a + b;', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'beginner' },
    { id: 'g:code:74', text: 'const add = (a, b) => a + b;', category: 'code', tags: ['code-js'], difficulty: 'beginner' },
    { id: 'g:code:75', text: 'console.log(`count is ${count}`);', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'beginner' },
    { id: 'g:code:76', text: 'throw new Error(`invalid input: ${JSON.stringify(input)}`);', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:77', text: 'return items.filter(Boolean).map(i => i.id);', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:78', text: 'Object.keys(obj).forEach(k => console.log(k, obj[k]));', category: 'code', tags: ['code-js'], difficulty: 'intermediate' },
    { id: 'g:code:79', text: 'new Map<string, number>([["a", 1], ["b", 2]]);', category: 'code', tags: ['code-js', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:80', text: 'const set = new Set([1, 2, 3, 3, 2, 1]);', category: 'code', tags: ['code-js'], difficulty: 'beginner' },

    // Python, Rust, C/C++, shell scripting (+20 for 0.1.2)
    { id: 'g:code:81', text: 'df = pd.read_csv("data.csv").dropna().reset_index(drop=True)', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:82', text: 'result = [x ** 2 for x in range(10) if x % 2 == 0]', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:83', text: 'from fastapi import FastAPI, HTTPException', category: 'code', tags: ['code-general'], difficulty: 'beginner' },
    { id: 'g:code:84', text: '@app.get("/items/{id}")\nasync def read(id: int): return {"id": id}', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:85', text: 'class User(BaseModel):\n    name: str\n    email: EmailStr', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:86', text: 'def embed(text: str) -> list[float]: return model.encode(text)', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:87', text: 'with open("log.txt") as f: lines = f.readlines()', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'beginner' },
    { id: 'g:code:88', text: 'torch.nn.functional.softmax(logits, dim=-1)', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:89', text: 'fn main() { println!("hello, {}!", name); }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'beginner' },
    { id: 'g:code:90', text: 'let mut v: Vec<i32> = Vec::new(); v.push(42);', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:91', text: 'match result { Ok(v) => println!("{v}"), Err(e) => eprintln!("{e}") }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:92', text: 'impl<T: Clone> Wrapper<T> { fn new(v: T) -> Self { Self { inner: v } } }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:93', text: 'let (tx, rx) = tokio::sync::mpsc::channel(32);', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:94', text: '#include <stdio.h>\nint main() { printf("ok\\n"); return 0; }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:95', text: 'for (int i = 0; i < n; ++i) { sum += arr[i]; }', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:96', text: 'struct Node { int val; struct Node* next; };', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:97', text: 'if [ -f "$FILE" ]; then echo "found"; else echo "missing"; fi', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:98', text: 'for f in *.log; do gzip "$f"; done', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'intermediate' },
    { id: 'g:code:99', text: 'case "$1" in start) up ;; stop) down ;; *) usage ;; esac', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },
    { id: 'g:code:100', text: 'trap "cleanup" EXIT INT TERM', category: 'code', tags: ['code-general', 'code-symbols'], difficulty: 'advanced' },

    // =============================================
    // CLI — shell commands, terminal one-liners
    // =============================================
    { id: 'g:cli:1', text: "git commit -m 'fix: resolve null pointer error'", category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:2', text: 'docker run -d -p 8080:80 --name app nginx:latest', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:3', text: 'ssh user@192.168.1.100 -i ~/.ssh/id_rsa -p 2222', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:4', text: "curl -X POST -H 'Content-Type: application/json' -d '{}'", category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:5', text: 'npm install --save-dev typescript @types/node vitest', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:6', text: 'git rebase -i HEAD~3 && git push --force-with-lease', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:7', text: 'grep -rn "TODO" src/ | wc -l', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'intermediate' },
    { id: 'g:cli:8', text: 'tar -czf backup.tar.gz ./src ./package.json', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:9', text: 'cat .env | xargs -I {} echo "export {}"', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:10', text: 'chmod 755 deploy.sh && ./deploy.sh --prod', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:11', text: "email@example.com https://api.dev/v2?q=1&limit=10", category: 'cli', tags: ['punctuation'], difficulty: 'intermediate' },
    { id: 'g:cli:12', text: 'file.txt -> backup/file.txt.bak #archived', category: 'cli', tags: ['punctuation'], difficulty: 'beginner' },
    { id: 'g:cli:13', text: 'kubectl get pods -n production --sort-by=.status.startTime', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:14', text: 'aws s3 sync ./dist s3://my-bucket --delete --acl public-read', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:15', text: 'find . -name "*.log" -mtime +7 -exec rm {} \\;', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:16', text: 'git status --short --branch', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:17', text: 'git checkout -b feature/new-login', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:18', text: 'git cherry-pick abc1234', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:19', text: 'git reflog --date=iso | head -20', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:20', text: 'git bisect start && git bisect bad HEAD && git bisect good v1.2.0', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:21', text: 'git stash push -m "wip: refactor auth"', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:22', text: 'git worktree add ../hotfix main', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:23', text: 'git log --oneline --graph --all', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:24', text: 'git diff HEAD~1 -- src/', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:25', text: 'git remote add upstream https://github.com/org/repo.git', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:26', text: 'docker compose up -d --build', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:27', text: 'docker exec -it app /bin/bash', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:28', text: 'docker logs -f --tail 100 api', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:29', text: 'docker build -t myapp:v1.2.3 .', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:30', text: 'docker ps -a --format "{{.Names}}: {{.Status}}"', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:31', text: 'kubectl apply -f deployment.yaml', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:32', text: 'kubectl describe pod api-7d9f', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:33', text: 'kubectl logs -f deploy/api --since=10m', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:34', text: 'kubectl port-forward svc/db 5432:5432', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:35', text: 'kubectl exec -it pod/shell -- /bin/sh', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:36', text: 'aws s3 cp ./build s3://deploy-bucket/ --recursive', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:37', text: 'gcloud compute instances list --filter="status=RUNNING"', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:38', text: 'gsutil rsync -r gs://src-bucket ./local', category: 'cli', tags: ['cli'], difficulty: 'advanced' },
    { id: 'g:cli:39', text: 'aws iam list-users --output json', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:40', text: 'curl -H "Authorization: Bearer $TOKEN" https://api.example.com/me', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:41', text: 'curl -X POST -d \'{"name":"ada"}\' -H "Content-Type: application/json" /users', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:42', text: 'curl -o file.zip -L https://example.com/archive.zip', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:43', text: 'cat data.json | jq \'.users[] | select(.active)\'', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:44', text: 'jq -r \'.items | length\' response.json', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'intermediate' },
    { id: 'g:cli:45', text: 'find . -type f -name "*.ts" | xargs wc -l', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'intermediate' },
    { id: 'g:cli:46', text: 'find /var/log -mtime +30 -delete', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:47', text: 'ssh -L 5432:localhost:5432 user@db.prod', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:48', text: 'rsync -avz --progress ./src user@host:/app', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:49', text: 'systemctl restart nginx', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:50', text: 'journalctl -u api.service -f --since "1 hour ago"', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:51', text: 'pnpm add -D vitest @vitest/ui', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:52', text: 'yarn workspace web add react-router-dom', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:53', text: 'bun run dev', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:54', text: 'npx create-next-app@latest my-app --typescript', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },
    { id: 'g:cli:55', text: 'npm run build && npm run test', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:56', text: 'ls -lah ~/.config', category: 'cli', tags: ['cli'], difficulty: 'beginner' },
    { id: 'g:cli:57', text: 'ps aux | grep node | awk \'{print $2}\'', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'advanced' },
    { id: 'g:cli:58', text: 'export PATH="$HOME/.local/bin:$PATH"', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'intermediate' },
    { id: 'g:cli:59', text: 'echo $? && exit 0', category: 'cli', tags: ['cli', 'symbols'], difficulty: 'beginner' },
    { id: 'g:cli:60', text: 'mkdir -p src/components/ui && touch src/components/ui/Button.tsx', category: 'cli', tags: ['cli'], difficulty: 'intermediate' },

    // =============================================
    // TECHNIQUE — finger, row, and hand isolation
    // Short, repetitive patterns to build muscle memory.
    // =============================================

    // Home row basics
    { id: 'g:tech:1', text: 'asdf jkl; asdf jkl; asdf jkl;', category: 'technique', tags: ['home-row'], difficulty: 'beginner' },
    { id: 'g:tech:2', text: 'asdfg hjkl; asdfg hjkl; asdfg', category: 'technique', tags: ['home-row'], difficulty: 'beginner' },
    { id: 'g:tech:3', text: 'dad sad fad lad lads sads fads', category: 'technique', tags: ['home-row'], difficulty: 'beginner' },
    { id: 'g:tech:4', text: 'a sad lad had a salad as a dad', category: 'technique', tags: ['home-row', 'left-hand'], difficulty: 'beginner' },
    { id: 'g:tech:5', text: 'fall gall hall jail kale lash', category: 'technique', tags: ['home-row'], difficulty: 'beginner' },

    // Index finger drills (f/v/r/t/g/b and j/n/u/y/h/m)
    { id: 'g:tech:6', text: 'fff vvv rrr fff vvv rrr fff vvv', category: 'technique', tags: ['index-fingers', 'left-hand'], difficulty: 'beginner' },
    { id: 'g:tech:7', text: 'jjj nnn uuu jjj nnn uuu jjj nnn', category: 'technique', tags: ['index-fingers', 'right-hand'], difficulty: 'beginner' },
    { id: 'g:tech:8', text: 'frf vfv rfr vvr frv frf vfv', category: 'technique', tags: ['index-fingers', 'left-hand'], difficulty: 'beginner' },
    { id: 'g:tech:9', text: 'jhj nun ujh jnu jhj nun ujh', category: 'technique', tags: ['index-fingers', 'right-hand'], difficulty: 'beginner' },
    { id: 'g:tech:10', text: 'frufuj rufurj frufuj rufurj', category: 'technique', tags: ['index-fingers'], difficulty: 'intermediate' },
    { id: 'g:tech:11', text: 'brave front bunch giant guard', category: 'technique', tags: ['index-fingers'], difficulty: 'intermediate' },

    // Middle finger drills (d/e/c and k/i/,)
    { id: 'g:tech:12', text: 'ded ded kik kik ded kik ded kik', category: 'technique', tags: ['middle-fingers'], difficulty: 'beginner' },
    { id: 'g:tech:13', text: 'deck deck kick kick deed keen', category: 'technique', tags: ['middle-fingers'], difficulty: 'beginner' },
    { id: 'g:tech:14', text: 'cede iced dike kiln deep keep', category: 'technique', tags: ['middle-fingers'], difficulty: 'intermediate' },

    // Ring finger drills (s/w/x and l/o/.)
    { id: 'g:tech:15', text: 'sws sws lol lol sws lol sws lol', category: 'technique', tags: ['ring-fingers'], difficulty: 'beginner' },
    { id: 'g:tech:16', text: 'slow slow lows lows owls sows', category: 'technique', tags: ['ring-fingers'], difficulty: 'beginner' },
    { id: 'g:tech:17', text: 'swoon wool ooze solo wool swoon', category: 'technique', tags: ['ring-fingers'], difficulty: 'intermediate' },

    // Pinky drills (a/q/z and ;/p//)
    { id: 'g:tech:18', text: 'aqa aqa ;p; ;p; aqa ;p; aqa ;p;', category: 'technique', tags: ['pinky-fingers'], difficulty: 'beginner' },
    { id: 'g:tech:19', text: 'papa quay zaps papa quay zaps', category: 'technique', tags: ['pinky-fingers'], difficulty: 'intermediate' },
    { id: 'g:tech:20', text: 'plaza pizza quota plaza pizza', category: 'technique', tags: ['pinky-fingers'], difficulty: 'intermediate' },

    // Left hand only
    { id: 'g:tech:21', text: 'stewardesses reserved crates after we served', category: 'technique', tags: ['left-hand'], difficulty: 'intermediate' },
    { id: 'g:tech:22', text: 'we tested a great brave face at the debate', category: 'technique', tags: ['left-hand'], difficulty: 'intermediate' },
    { id: 'g:tech:23', text: 'best case scenarios rarely appear at startups', category: 'technique', tags: ['left-hand'], difficulty: 'advanced' },

    // Right hand only
    { id: 'g:tech:24', text: 'pump junk milk hymn pony plum pulp', category: 'technique', tags: ['right-hand'], difficulty: 'intermediate' },
    { id: 'g:tech:25', text: 'my pink lion ate only pumpkin pulp', category: 'technique', tags: ['right-hand'], difficulty: 'intermediate' },
    { id: 'g:tech:26', text: 'you jump him up my hill in noon hour', category: 'technique', tags: ['right-hand'], difficulty: 'advanced' },

    // Top row drills (qwerty row)
    { id: 'g:tech:27', text: 'qwe rty uio pqwe rty uio pqwe rty', category: 'technique', tags: ['top-row'], difficulty: 'beginner' },
    { id: 'g:tech:28', text: 'were pour your type quiet reporter', category: 'technique', tags: ['top-row'], difficulty: 'intermediate' },
    { id: 'g:tech:29', text: 'we were ripe to pour out your report', category: 'technique', tags: ['top-row'], difficulty: 'intermediate' },

    // Bottom row drills (zxcv row)
    { id: 'g:tech:30', text: 'zxc vbn m,. zxc vbn m,. zxc vbn', category: 'technique', tags: ['bottom-row', 'symbols'], difficulty: 'beginner' },
    { id: 'g:tech:31', text: 'my man can back a van in the nook', category: 'technique', tags: ['bottom-row'], difficulty: 'intermediate' },
    { id: 'g:tech:32', text: 'examine maximum oxygen back in minvan', category: 'technique', tags: ['bottom-row'], difficulty: 'advanced' },

    // Common bigrams
    { id: 'g:tech:33', text: 'th he an in er on at en nd re', category: 'technique', tags: ['bigrams'], difficulty: 'beginner' },
    { id: 'g:tech:34', text: 'the and for not but you all any can', category: 'technique', tags: ['bigrams', 'common-words'], difficulty: 'beginner' },
    { id: 'g:tech:35', text: 'tion sion ight ough ould ance ence', category: 'technique', tags: ['bigrams'], difficulty: 'intermediate' },

    // Number row
    { id: 'g:tech:36', text: '1 2 3 4 5 6 7 8 9 0 1 2 3 4 5', category: 'technique', tags: ['number-row'], difficulty: 'beginner' },
    { id: 'g:tech:37', text: '12 34 56 78 90 12 34 56 78 90', category: 'technique', tags: ['number-row'], difficulty: 'beginner' },
    { id: 'g:tech:38', text: 'port 8080 host 127.0.0.1 id 4200', category: 'technique', tags: ['number-row', 'symbols'], difficulty: 'intermediate' },
    { id: 'g:tech:39', text: 'version 2.1.4 built on 2026-04-11', category: 'technique', tags: ['number-row', 'symbols'], difficulty: 'intermediate' },

    // Alternating hands (smooth flow)
    { id: 'g:tech:40', text: 'the their they when there then them', category: 'technique', tags: ['bigrams'], difficulty: 'beginner' },
  ],
};
